### ISSUE TITLE
private group bug

### ISSUE THREAD

**Issue by vlab97** [HeimanPictures/Feedback-bot#6]
also interested in the parameter "OWNER_ID". when using a  private group ID, the bot does not work correctly.![image](https://user-images.githubusercontent.com/44323817/212543814-894c854f-883d-4621-99b7-abbd0c0dc114.jpeg)

**Comment by HeimanPictures** [comment]
Dear @vlab97, can you give me more input on this issue like, how? when? where? (problem faced by you). To check issue how you faced and solving it.

**Comment by vlab97** [comment]
In this case, the bot perceives the responses to messages incorrectly. He registers them as new messages that need to be forwarded to a private chat.

**Comment by HeimanPictures** [comment]
In OWNER_ID what did you enter?

**Comment by vlab97** [comment]
> @vlab97, In OWNER_ID what did you enter, your id or private group?

private group

**Comment by HeimanPictures** [comment]
add your id not private group, your issue will be solved
